Repository nathanielmillard/rancid-tomatillos, pull requests merged in 2020-10, with the labels that each got.

#5 Set up
  .gitignore
  README.md
  package-lock.json
  package.json
  public/favicon.ico
  public/index.html
  public/logo192.png
  public/logo512.png
  public/manifest.json
  public/robots.txt
  pull_request_template.md
  src/App.css
  src/App.js
  src/App.test.js
  src/components/Custom-Button.js
  src/components/Form-Input.js
  src/components/MovieMain.js
  src/components/MovieShowPage.js
  src/components/MovieTile.js
  src/components/NavBar.js
  src/components/Sign-In.js
  src/index.css
  src/index.js
  src/serviceWorker.js
  src/setupTests.js
Labels: documentation

#9 Nd basic components structure
  package-lock.json
  package.json
  src/App.css
  src/App.js
  src/App.scss
  src/components/MovieMain.js
  src/components/MovieTile.js
  src/components/NavBar.js
Labels: enhancement

#22 Nd initial testing
  package-lock.json
  package.json
  src/App.js
  src/App.test.js
  src/components/Custom-Button/Custom-Button.js
  src/components/Form-Input/Form-Input.js
  src/components/MovieMain/MovieMain.js
  src/components/MovieShowPage/MovieShowPage.js
  src/components/MovieTile/MovieTile.js
  src/components/MovieTile/MovieTile.test.js
  src/components/Navbar/NavBar.js
  src/components/Navbar/NavBar.test.js
  src/components/Sign-In/Sign-In.js
  src/components/Sign-In/Sign-In.test.js
  src/setUpTests.js
  src/setupTests.js
Labels: documentation, enhancement, test driven development

#27 Movie Show Page
  src/App.js
  src/App.scss
  src/components/MovieShowPage/MovieShowPage.js
  src/components/MovieTile/MovieTile.js
Labels: documentation

#32 Nd show add ratings
  src/App.js
  src/App.scss
  src/components/MovieMain/MovieMain.js
  src/components/MovieShowPage/MovieShowPage.js
  src/components/MovieTile/MovieTile.js
  src/components/Navbar/NavBar.js
  src/components/Sign-In/Sign-In.js
Labels: documentation, enhancement

#41 Testing Refactors
  package-lock.json
  package.json
  src/App.js
  src/apiCalls.js
  src/components/App/App.js
  src/components/App/App.scss
  src/components/App/App.test.js
  src/components/MovieMain/MovieMain.js
  src/components/MovieMain/MovieMain.test.js
  src/components/MovieShowPage/MovieShowPage.js
  src/components/MovieTile/MovieTile.test.js
  src/components/Navbar/NavBar.test.js
  src/components/Sign-In/Sign-In.js
  src/index.js
Labels: documentation

#40 Nd remove ratings
  src/apiCalls.js
  src/components/MovieMain/MovieMain.js
  src/components/MovieShowPage/MovieShowPage.js
  src/components/Navbar/NavBar.test.js
  src/components/Sign-In/Sign-In.js
  src/components/Sign-In/Sign-In.test.js
Labels: documentation, enhancement, test driven development

#48 Prop types
  package.json
  src/components/MovieMain/MovieMain.js
  src/components/MovieShowPage/MovieShowPage.js
  src/components/MovieTile/MovieTile.js
  src/components/Navbar/NavBar.js
  src/components/Sign-In/Sign-In.js
Labels: enhancement

#49 Nd comments
  src/apiCalls.js
  src/components/Comment/Comment.js
  src/components/Comment/Comment.scss
  src/components/Comment/Comment.test.js
  src/components/Comments/Comments.js
  src/components/Comments/Comments.scss
  src/components/Comments/Comments.test.js
  src/components/MovieShowPage/MovieShowPage.js
  src/components/MovieShowPage/MovieShowPage.scss
Labels: documentation, enhancement

#54 Nd testing comments
  src/apiCalls.js
  src/components/Comment/Comment.test.js
  src/components/Comments/Comments.js
  src/components/Comments/Comments.test.js
Labels: documentation, enhancement, test driven development

#55 Nm favoriting
  src/apiCalls.js
  src/components/App/App.js
  src/components/FavoriteButton/FavoriteButton.js
  src/components/FavoriteButton/FavoriteButton.scss
  src/components/MovieMain/MovieMain.js
  src/components/MovieShowPage/MovieShowPage.js
  src/components/MovieShowPage/MovieShowPage.scss
  src/components/MovieTile/MovieTile.js
  src/components/MovieTile/MovieTile.scss
  src/components/Navbar/NavBar.js
  src/images/favorite-button.svg
  src/images/rating-star-active.svg
  src/images/rating-star-inactive.svg
  src/images/unfavorite-button.svg
Labels: documentation, enhancement

#56 Nm testing and refining
  package-lock.json
  package.json
  src/components/App/App.js
  src/components/App/App.test.js
  src/components/Comments/Comments.js
  src/components/Comments/Comments.test.js
  src/components/FavoriteButton/FavoriteButton.js
  src/components/FavoriteButton/FavoriteButton.scss
  src/components/FavoriteButton/FavoriteButton.test.js
  src/components/Form-Input/Form-Input.js
  src/components/MovieMain/MovieMain.js
  src/components/MovieMain/MovieMain.test.js
  src/components/MovieShowPage/MovieShowPage.js
  src/components/MovieShowPage/MovieShowPage.scss
  src/components/MovieShowPage/MovieShowPage.test.js
  src/components/MovieTile/MovieTile.js
  src/components/MovieTile/MovieTile.scss
  src/components/MovieTile/MovieTile.test.js
  src/components/Navbar/NavBar.js
  src/components/Navbar/NavBar.test.js
  src/components/Sign-In/Sign-In.js
  src/components/Sign-In/Sign-In.scss
  src/components/Sign-In/Sign-In.test.js
Labels: documentation, enhancement
